# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PI_NAME', models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
