# Generated by Django 2.0.1 on 2018-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='PI_NAME',
        ),
        migrations.AddField(
            model_name='grant',
            name='activity',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='administering_ic',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='application_id',
            field=models.CharField(default='null', max_length=12),
        ),
        migrations.AddField(
            model_name='grant',
            name='application_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='arra_funded',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='award_notice_date',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='pi_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
