# Generated by Django 2.0.1 on 2018-01-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0002_auto_20180104_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='arra_funded',
        ),
        migrations.AddField(
            model_name='grant',
            name='budget_end',
            field=models.DateField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='budget_start',
            field=models.DateField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='core_proect_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='ed_inst_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='full_project_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='funding_ics',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='funding_mechanism',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='award_notice_date',
            field=models.DateField(max_length=16, null=True),
        ),
    ]
