# Generated by Django 2.0.1 on 2018-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0003_auto_20180106_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='award_notice_date',
        ),
        migrations.AddField(
            model_name='grant',
            name='FY',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='ic_name',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_dept',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_district',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='org_zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='phr',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
