# Generated by Django 2.0.1 on 2018-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0005_auto_20180106_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='direct_cost_amt',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='indirect_cost_amt',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='study_section',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='study_section_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='subproject_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='support_year',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_cost',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_cost_sub_project',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
