# Generated by Django 2.0.1 on 2018-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0006_auto_20180106_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='FY',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='activity',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='administering_ic',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='application_id',
            field=models.CharField(blank=True, default='null', max_length=12),
        ),
        migrations.AlterField(
            model_name='grant',
            name='application_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='budget_end',
            field=models.DateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='budget_start',
            field=models.DateField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='core_proect_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='direct_cost_amt',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='ed_inst_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='full_project_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='funding_ics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='funding_mechanism',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='ic_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='indirect_cost_amt',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_dept',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_district',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='phr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi_ids',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='project_terms',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='project_title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='study_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='study_section_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='subproject_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='support_year',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='total_cost',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='total_cost_sub_project',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
    ]
