# Generated by Django 2.0.1 on 2018-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0007_auto_20180106_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='FY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='direct_cost_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='indirect_cost_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='org_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='support_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='total_cost_sub_project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
