# Generated by Django 2.0.1 on 2018-01-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0008_auto_20180106_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='pi_ids',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
