# Generated by Django 2.0.1 on 2018-01-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0009_auto_20180106_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='abstract_text',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
