# Generated by Django 2.0.1 on 2018-01-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0010_grant_abstract_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='application_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
