# Generated by Django 2.0.1 on 2018-01-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0011_auto_20180106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='abstract_text',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
