# Generated by Django 2.0.1 on 2018-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0012_auto_20180106_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='funding_ics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
