# Generated by Django 2.0.1 on 2018-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0013_auto_20180107_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='ed_inst_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi_ids',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
