# Generated by Django 2.0.1 on 2018-01-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0015_auto_20180108_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grant_Publications',
            new_name='Grant_Publication',
        ),
    ]
