# Generated by Django 2.0.1 on 2018-01-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0016_auto_20180108_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='core_proect_num',
            new_name='core_project_num',
        ),
    ]
