# Generated by Django 2.0.1 on 2018-01-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0017_auto_20180108_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(max_length=9000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-FY', '-total_cost']},
        ),
    ]
