# Generated by Django 2.0.1 on 2018-01-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0018_auto_20180108_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
