# Generated by Django 2.0.1 on 2018-01-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0019_auto_20180108_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapApp.Grant')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapApp.Keyword')),
            ],
        ),
    ]
