# Generated by Django 2.0.1 on 2018-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0020_keyword_keyword_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword_grant',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='keyword_grant',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='grants',
            field=models.ManyToManyField(to='CapApp.Grant'),
        ),
        migrations.AddField(
            model_name='keyword_grant',
            name='nothing',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
