# Generated by Django 2.0.1 on 2018-01-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0021_auto_20180109_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='searches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
