# Generated by Django 2.0.1 on 2018-01-11 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0022_auto_20180110_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-searches']},
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), size=None), null=True, size=None),
        ),
    ]
