# Generated by Django 2.0.1 on 2018-01-11 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0023_auto_20180111_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='pi_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), null=True, size=None),
        ),
    ]
