# Generated by Django 2.0.1 on 2018-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0025_auto_20180111_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='affiliation',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
