# Generated by Django 2.0.1 on 2018-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0027_auto_20180114_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
