# Generated by Django 2.0.1 on 2018-01-15 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0028_auto_20180114_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='related_grants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), null=True, size=None),
        ),
    ]
