# Generated by Django 2.0.1 on 2018-01-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0031_auto_20180115_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related_grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_project_num', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Keyword_grant',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='related_grants',
        ),
        migrations.AddField(
            model_name='related_grant',
            name='grants',
            field=models.ManyToManyField(to='CapApp.Grant'),
        ),
    ]
