# Generated by Django 2.0.1 on 2018-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0032_auto_20180115_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='pi_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
