# Generated by Django 2.0.1 on 2018-01-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0033_auto_20180115_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
