# Generated by Django 2.0.1 on 2018-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0034_publication_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='suffix',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_funding_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
