# Generated by Django 2.0.1 on 2018-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0035_auto_20180117_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='total_direct_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_indirect_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
