# Generated by Django 2.0.1 on 2018-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0036_auto_20180117_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_grant',
            name='total_direct_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='related_grant',
            name='total_funding_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='related_grant',
            name='total_indirect_of_core_numb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
