# Generated by Django 2.0.1 on 2018-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0037_auto_20180117_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='grant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
