# Generated by Django 2.0.1 on 2018-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0038_auto_20180117_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='grant_count_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_count_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_count_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_count_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost_18',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
