# Generated by Django 2.0.1 on 2018-01-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0039_auto_20180117_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
