# Generated by Django 2.0.1 on 2018-01-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0040_auto_20180117_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='dp1_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='dp1_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='dp2_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='dp2_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='f31_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='f31_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='f32_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='f32_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='k99_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='k99_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r00_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r00_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r01_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r01_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r35_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='r35_total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
