# Generated by Django 2.0.1 on 2018-01-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0042_auto_20180120_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='grant_count_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_direct_cost_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_indirect_cost_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='grant_total_cost_14',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
