# Generated by Django 2.0.1 on 2018-01-23 16:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0043_auto_20180121_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
