# Generated by Django 2.0.1 on 2018-01-23 19:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0046_keyword_states_top_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='scatterplot_array',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
