# Generated by Django 2.0.1 on 2018-01-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapApp', '0047_keyword_scatterplot_array'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-total_funding_of_core_numb', '-FY']},
        ),
    ]
